version: '3'
services:
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=tasks
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3307:3306
  rabbitmq:
    image: rabbitmq:3.10.5-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
