spring:
  datasource:
    username: root
    password: secret
    url: jdbc:mysql://localhost:3307/tasks
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: 'classpath:db/migrations'
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit

executors:
  thread-pool:
    keep-alive-time: 1m
    await-termination: 20s

tasks:
  main-thread-pool: 3
  sub-thread-pool: 12
  cache:
    enabled: true
    entry-lifetime: 1h
  delay:
    min-millis: 3000
    max-millis: 10000
